export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS_LOADING = 'GET_TICKETS_LOADING';
export const GET_TICKETS_ERROR = 'GET_TICKETS_ERROR';
export const SORT_TICKETS_BY_PRICE = 'SORT_TICKETS_BY_PRICE';
export const SORT_TICKETS_BY_TIME = 'SORT_TICKETS_BY_TIME';
export const RESET_TICKETS = 'RESET_TICKETS';
export const FILTER_TICKETS_BY_TRANSFER_COUNT = 'FILTER_TICKETS_BY_TRANSFER_COUNT';
